name: pyinstaller
on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v3
        with:
          name: sha256-windows.exe
          path: dist/sha256.exe

  build-on-windows2:
    runs-on: windows-2022
    needs: build-on-windows
    steps:
      - name: download exe file
        uses: actions/download-artifact@v3
        with:
          name: sha256-windows.exe
      - name: text exe file
        run: |
          ls
          ./sha256.exe sha256.exe
