name: secret_workflow
on: workflow_dispatch

env:
  DB_USERNAME: ${{ vars.db_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3
      - name: check user name
        run: echo "u=${{ env.DB_USERNAME }}"
      - name: check password
        run: echo "p=${{ env.DB_PASSWORD }}"
      - name: Test with javascript
        run: node secrets.js
