name: workflow_env
on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday
  DB_Password: ${{ secrets.DB_PASSWORD }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! and show"
      - name: Reveal password
        run: echo "p=${{ env.DB_PASSWORD }}"
      - name: test with python
        run: python secrets.py
        env:
          $First_name: Mona
