name: secret_workflow
on: workflow_dispatch

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3
      - name: check password
        run: echo "p=${{ env.DB_PASSWORD }}"
      - name: test with python
        run: python secrets.py
        env:
          $First_name: Mona
