name: secret_workflow
on: workflow_dispatch

jobs:
  greeting_dev:
    environment: test
    env:
      DB_USERNAME: ${{ vars.db_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3
      - name: check user name
        run: echo "u=${{ env.DB_USERNAME }}"
      - name: Test with javascript
        run: node secrets.js
  prod_greeting:
    environment: prod
    env:
      DB_USERNAME: ${{ vars.db_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3
      - name: check user name
        run: echo "u=${{ env.DB_USERNAME }}"
      - name: Test with javascript
        run: node secrets.js
